version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: todo123
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: